= Agents Governance Profile

A profile of several Semantic Web / Knowledge Graph models (ontologies) for the representation of sophisticated Agent (people and organisations) relations, mainly for the purposes of the governance of Entities (things), in particular data.

== Profile Resources

The contents of this repository form a "Profile", that is a Standard that constrains and extends other Standards, as described by https://www.w3.org/TR/dx-prof/[The Profiles Vocabulary].

See the https://w3id.org/idn/def/agp[Profile Declaration] for details of all the profile parts (Resources).

== Licensing & Rights

The creators and maintainers of this model wish for it to be available for use as widely as possible. The model is thus licensed using the permissive, and pretty standard, https://creativecommons.org/licenses/by/4.0/[Creative Commons BY 4.0]  license, a copy of the deed of which is in the file LICENSE.

This software is copyright as follows:

(c) Indigenous Data Network, 2022

== Contact

Please contact the Indigenous Data Network maintainers of this code for all issues:

_Lead Developer_: +
*Nicholas Car* +
GitHub: https://github.com/nicholascar[@nicholascar] +
Email: nick@kurrawong.net +

_Project Owner_: +
*Sandra Silcot* +
GitHub: https://github.com/ssilcot[@ssilcot] +

_Owner Organisation_ +
*Indigenous Data Network* +
https://idnau.org